import Head from 'next/head'
import { useContext } from "react";
import { GlobalContext } from "@utils/GlobalContext";
import Link from 'next/link';
import SkeletonArtistList from '@components/SkeletonArtistList';

export default function Artists() {
  const { darkMode, setDarkMode } = useContext(GlobalContext);

  return (
    <>
      <Head>
        <title>Artists List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen p-8 md:p-12">
        <div className="max-w-lg mx-auto">

          <nav className="flex justify-between mb-8 gap-x-4">
            <Link href="/">
              <a className="text-blue-500 hover:text-blue-600 font-medium transition-all hover:cursor-pointer">Songs</a>
            </Link>
            <Link href="/artists">
              <a className="text-blue-500 hover:text-blue-600 font-medium transition-all hover:cursor-pointer">Artists</a>
            </Link>
            <div onClick={() => setDarkMode(!darkMode)} className="transition-all cursor-pointer w-12 h-7 dark:bg-blue-500 bg-neutral-200 rounded-full relative">
              <div className="h-5 w-5 bg-white rounded-full absolute top-1 transition-all dark:left-6 left-1"></div>
            </div>
          </nav>

          <div className="flex items-center justify-between">
            <h1 className="text-neutral-700 dark:text-gray-100 text-2xl font-bold">Artist List</h1>
          </div>

          <div className="mt-6 grid grid-cols-1 md:grid-cols-2 gap-4">

            <SkeletonArtistList />
            <SkeletonArtistList />
            <SkeletonArtistList />
            <SkeletonArtistList />

          </div>

        </div>
      </main>
    </>
  )
}
