import Head from 'next/head';
import { useContext } from "react";
import { GlobalContext } from "@utils/GlobalContext";

export default function Home() {
  const [darkMode, setDarkMode] = useContext(GlobalContext);

  return (
    <>
      <Head>
        <title>Next Storybook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen flex items-center justify-center">
        <h1 className="text-neutral-700 dark:text-gray-100 text-2xl font-bold">Next Storybook</h1>
      </main>
    </>
  )
}
